-- MySQL Script generated by MySQL Workbench
-- Mon May 24 19:22:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_cs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cs` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_cs` ;

-- -----------------------------------------------------
-- Table `db_cs`.`division`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`division` (
  `division_id` INT NOT NULL,
  `division_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`division_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_cs`.`rent_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`rent_type` (
  `rent_type_id` INT NOT NULL,
  `rent_type_name` VARCHAR(45) NULL DEFAULT NULL,
  `rent_type_cost` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`rent_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_cs`.`service_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`service_type` (
  `service_type_id` INT NOT NULL,
  `service_type_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`service_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_cs`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`service` (
  `service_id` INT NOT NULL,
  `service_name` VARCHAR(45) NOT NULL,
  `service_area` INT NULL DEFAULT NULL,
  `service_max_people` INT NULL DEFAULT NULL,
  `service_cost` DOUBLE NOT NULL,
  `rent_type_id` INT NOT NULL,
  `service_type_id` INT NOT NULL,
  `standard_room` VARCHAR(45) NULL DEFAULT NULL,
  `description_other_convenience` VARCHAR(45) NULL,
  `pool_area` DOUBLE NULL,
  `number_of_floors` INT NULL DEFAULT NULL,
  PRIMARY KEY (`service_id`),
  INDEX `IDKieuThue` (`rent_type_id` ASC) VISIBLE,
  INDEX `IDLoaiDichVu` (`service_type_id` ASC) VISIBLE,
  CONSTRAINT `dichvu_ibfk_1`
    FOREIGN KEY (`rent_type_id`)
    REFERENCES `db_cs`.`rent_type` (`rent_type_id`),
  CONSTRAINT `dichvu_ibfk_2`
    FOREIGN KEY (`service_type_id`)
    REFERENCES `db_cs`.`service_type` (`service_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_cs`.`attach_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`attach_service` (
  `attach_service_id` INT NOT NULL,
  `attach_service_name` VARCHAR(45) NOT NULL,
  `attach_service_cost` DOUBLE NOT NULL,
  `attach_service_unit` INT NOT NULL,
  `attach_service_status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`attach_service_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_cs`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`position` (
  `position_id` INT NOT NULL,
  `position_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`position_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_cs`.`education_degree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`education_degree` (
  `education_degree_id` INT NOT NULL,
  `education_degree_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`education_degree_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_cs`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`user` (
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cs`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`employee` (
  `employee_id` INT NOT NULL,
  `employee_name` VARCHAR(45) NOT NULL,
  `employee_birthday` DATE NOT NULL,
  `employee_id_card` VARCHAR(45) NOT NULL,
  `employee_salary` VARCHAR(45) NOT NULL,
  `employee_phone` VARCHAR(45) NOT NULL,
  `employee_email` VARCHAR(45) NULL DEFAULT NULL,
  `employee_address` VARCHAR(45) NULL DEFAULT NULL,
  `position_id` INT NOT NULL,
  `education_degree_id` INT NOT NULL,
  `division_id` INT NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `IDViTri` (`position_id` ASC) VISIBLE,
  INDEX `IDTrinhDo` (`education_degree_id` ASC) VISIBLE,
  INDEX `IDBoPhan` (`division_id` ASC) VISIBLE,
  INDEX `fk_employee_user1_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `nhanvien_ibfk_1`
    FOREIGN KEY (`position_id`)
    REFERENCES `db_cs`.`position` (`position_id`),
  CONSTRAINT `nhanvien_ibfk_2`
    FOREIGN KEY (`education_degree_id`)
    REFERENCES `db_cs`.`education_degree` (`education_degree_id`),
  CONSTRAINT `nhanvien_ibfk_3`
    FOREIGN KEY (`division_id`)
    REFERENCES `db_cs`.`division` (`division_id`),
  CONSTRAINT `fk_employee_user1`
    FOREIGN KEY (`username`)
    REFERENCES `db_cs`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_cs`.`customer_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`customer_type` (
  `customer_type_id` INT NOT NULL,
  `customer_type_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_cs`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`customer` (
  `customer_id` INT NOT NULL,
  `customer_type_id` INT NOT NULL,
  `customer_name` VARCHAR(45) NOT NULL,
  `customer_birthday` DATE NOT NULL,
  `customer_gender` BIT(1) NOT NULL,
  `customer_id_card` VARCHAR(45) NOT NULL,
  `customer_phone` VARCHAR(45) NOT NULL,
  `customer_email` VARCHAR(45) NULL DEFAULT NULL,
  `customer_address` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `IDLoaiKhach` (`customer_type_id` ASC) VISIBLE,
  CONSTRAINT `khachhang_ibfk_1`
    FOREIGN KEY (`customer_type_id`)
    REFERENCES `db_cs`.`customer_type` (`customer_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_cs`.`contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`contract` (
  `contract_id` INT NOT NULL,
  `contract_start_date` DATETIME NOT NULL,
  `contract_end_date` DATETIME NOT NULL,
  `contract_deposit` DOUBLE NOT NULL,
  `contract_total_money` DOUBLE NOT NULL,
  `employee_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  PRIMARY KEY (`contract_id`),
  INDEX `IDNhanVien` (`employee_id` ASC) VISIBLE,
  INDEX `IDKhachHang` (`customer_id` ASC) VISIBLE,
  INDEX `IDDichVu` (`service_id` ASC) VISIBLE,
  CONSTRAINT `hopdong_ibfk_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `db_cs`.`employee` (`employee_id`),
  CONSTRAINT `hopdong_ibfk_2`
    FOREIGN KEY (`customer_id`)
    REFERENCES `db_cs`.`customer` (`customer_id`),
  CONSTRAINT `hopdong_ibfk_3`
    FOREIGN KEY (`service_id`)
    REFERENCES `db_cs`.`service` (`service_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_cs`.`contract_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`contract_detail` (
  `contract_detail_id` INT NOT NULL,
  `contract_id` INT NOT NULL,
  `attach_service_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`contract_detail_id`),
  INDEX `IDHopDong` (`contract_id` ASC) VISIBLE,
  INDEX `IDDichVuDiKem` (`attach_service_id` ASC) VISIBLE,
  CONSTRAINT `hopdongchitiet_ibfk_1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `db_cs`.`contract` (`contract_id`),
  CONSTRAINT `hopdongchitiet_ibfk_2`
    FOREIGN KEY (`attach_service_id`)
    REFERENCES `db_cs`.`attach_service` (`attach_service_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_cs`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`role` (
  `role_id` INT NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cs`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cs`.`user_role` (
  `role_id` INT NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`role_id`, `username`),
  INDEX `fk_table1_user1_idx` (`username` ASC) VISIBLE,
  CONSTRAINT `fk_table1_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `db_cs`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_user1`
    FOREIGN KEY (`username`)
    REFERENCES `db_cs`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
